INSERT INTO users
    (username, password, first_name, last_name, email, highscore)
VALUES
    ('sandy',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Sandy',
        'Spanik',
        'sandy@gmail.com',
        1000),
    ('fergus',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Fergus',
        'Cullen',
        'fergus@gmail.com', 900),
    ('player1',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'testuser@gmail.com', 0),
    ('player2',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Also',
        'Testuser',
        'fergus@gmail.com', 800),
    ('player3',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Robert',
        'Gordon',
        'sandy@gmail.com', 0),
    ('player4',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Nico',
        'Smiley',
        'fergus@gmail.com', 0),
    ('player5',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Lana',
        'Blana',
        'sandy@gmail.com', 0),
    ('player6',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Rita',
        'Skeeter',
        'fergus@gmail.com', 500),
    ('player9',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Harry',
        'Potter',
        'fergus@gmail.com', 0),
    ('player7',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Barry',
        'Trotter',
        'sandy@gmail.com', 0),
    ('player8',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Dobby',
        'Houself',
        'fergus@gmail.com', 0);

/* INSERT INTO highscores
    (username, highscore)
VALUES
    ('sandy', 1000),
    ('fergus', 900),
    ('player1', 800),
    ('player2', 700),
    ('player3', 600),
    ('player4', 500),
    ('player5', 400),
    ('player6', 300),
    ('player7', 200),
    ('player8', 100),
    ('player9', 500); */